# name: basic
# on: [push]
# jobs:
#   cypress-run:
#     runs-on: ubuntu-20.04

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Cypress run
#         uses: cypress-io/github-action@v2
#         fail-fast: false
#         matrix:
#         containers: [1, 2]
#         with:
#           command: npm run cy:run
#         # when setting "plain" environment variables
#         # if we want to pass Cypress to read them
#         # we need to prefix them with "CYPRESS_"
#         # https://on.cypress.io/environment-variables

name: Parallel Cypress Tests

on: [push]

jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          command: npm run cy:run
          record: true
          parallel: true
      - name: Generate Allure report
        if: always()
        uses: afiore/action-allure-report@v0.1.0

      - name: Commit report results
        if: always()
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add allure-report -f
            git add allure-results -f
            git add allure-history -f
            git commit -m "[chore] autogenerate Allure report" -a
      - name: Push changes
        if: always()
        uses: ad-m/github-push-action@master
        with:
            github_token: '${{ secrets.GITHUB_TOKEN }}'
            force: true
